services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    environment:
      - PORT=8080
      - STAGE=local
      - SESSION_SECRET=secret
      - REDIS_URL=redis://redis:6379
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - STEAM_API_KEY=${STEAM_API_KEY}
      - STEAM_RETURN_URL=${STEAM_RETURN_URL}
      - STEAM_REALM=${STEAM_REALM}
      - FRONTEND_URL=${FRONTEND_URL}
      - DOCS_TOKEN=${DOCS_TOKEN}
      - QUICKNODE_URI=${QUICKNODE_URI}
      - MONGODB_URI=mongodb://mongo:27017/database
      - VENLY_CLIENT_ID=${VENLY_CLIENT_ID}
      - VENLY_CLIENT_SECRET=${VENLY_CLIENT_SECRET}
      - VENLY_APPLICATION_ID=${VENLY_APPLICATION_ID}
      - MORALIS_API_KEY=${MORALIS_API_KEY}
      - API_KEY=${API_KEY}
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
    command: yarn start
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - 6379:6379
  mongo:
    image: mongo
    ports:
      - 27017:27017
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: 'database'
  cronjobs:
    build: ./cronjobs
    volumes:
      - ./cronjobs:/app
    command: yarn start
    environment:
      - REDIS_IO_HOST=${REDIS_IO_HOST}
      - REDIS_IO_PORT=${REDIS_IO_PORT}
      - REDIS_IO_PASSWORD=${REDIS_IO_PASSWORD}
      - PEPPER=${PEPPER}
      - VENLY_CLIENT_ID=${VENLY_CLIENT_ID}
      - VENLY_CLIENT_SECRET=${VENLY_CLIENT_SECRET}
      - VENLY_APPLICATION_ID=${VENLY_APPLICATION_ID}
      - STAGE=${STAGE}
      - MONGODB_URI=${MONGODB_URI}
      - SLACK_URL=${SLACK_URL}
    depends_on:
      - mongo
