name: Docker Image CI

on:
  push:
    branches: [ backend-develop ]
  pull_request:
    branches: [ backend-develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo "Created!"
