name: Backend-CI/CD Production Deploy

on:
  workflow_dispatch:

env:
  REGISTRY_NAME: 'webserver-production-ecr'
  SERVICE_NAME: 'webserver-production-service'
  CLUSTER_NAME: 'webserver-production-cluster'
  CONTAINER_NAME: 'webserver-production-ecs-container'
  TASK_DEFINITION_FAMILY: 'webserver-production-ecs-task-definition'

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-ecs
        with:
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws-region: ${{ secrets.AWS_REGION_PRODUCTION }}
          registry-name: ${{ env.REGISTRY_NAME }}
          service-name: ${{ env.SERVICE_NAME }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          container-name: ${{ env.CONTAINER_NAME }}
          task-definition-family: ${{ env.TASK_DEFINITION_FAMILY }}
