name: Backend-CI/CD Development Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/backend/src/*'

env:
  REGISTRY_NAME: 'webserver-develop-ecr'
  SERVICE_NAME: 'webserver-develop-service'
  CLUSTER_NAME: 'webserver-develop-cluster'
  CONTAINER_NAME: 'webserver-develop-ecs-container'
  TASK_DEFINITION_FAMILY: 'webserver-develop-ecs-task-definition'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn nx run-many --target=lint --projects=backend
      - run: yarn nx run-many --target=test --projects=backend
  deploy:
    name: Deploy Develop
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-ecs
        with:
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOP }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOP }}
          aws-region: ${{ secrets.AWS_REGION_DEVELOP }}
          registry-name: ${{ env.REGISTRY_NAME }}
          service-name: ${{ env.SERVICE_NAME }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          container-name: ${{ env.CONTAINER_NAME }}
          task-definition-family: ${{ env.TASK_DEFINITION_FAMILY }}
