name: Test CI

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Test
        required: false

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        shell: bash
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          echo "GIT_NAME_SLUG=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          echo "RELEASE=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Debug
        run: |
          echo ${{ env.GIT_NAME_SLUG }}
          echo ${{ env.BRANCH }}
          echo ${{ env.RELEASE }}
